io.write("Введите координаты первой вершины: ")
a1= tonumber(io.read("*n"))
a2= tonumber(io.read("*n"))
io.write("Введите координаты второй вершины: ")
b1= tonumber(io.read("*n"))
b2= tonumber(io.read("*n"))
io.write("Введите координаты третей вершины: ")
c1= tonumber(io.read("*n"))
c2= tonumber(io.read("*n"))
ab= math.sqrt((b1-a1)*(b1-a1)+(b2-a2)*(b2-a2))
bc= math.sqrt((c1-b1)*(c1-b1)+(c2-b2)*(c2-b2))
ac= math.sqrt((c1-a1)*(c1-a1)+(c2-a2)*(c2-a2))
p=ab+bc+ac
s=math.sqrt(p/2 *(p/2-ab)*(p/2-bc)*(p/2-ac))
print("Стороны треугольника равны: ")
print("a= ", ab)
print("b= ", bc)
print("c= ", ac)
print("Периметр треугольника равен:", p)
print("Площадь треугольника равна:", s)
